# Inherit the same environment as the root SConstruct 

Import('env')

env.Library(
    target = 'logging',
    source = [
        'mta_storage.cc',
        'event_dispatcher.tpp',
        'mta_logger.cc',
        'mta_metrics_builder.cc',
        'mta_metrics.cc',
        'timing_storage.cc',
        'timing_logger.cc',
        'timing_metrics_builder.cc',
        'timing_metrics.cc',
    ],
    CPPPATH = ['.']
)

env.Append(CPPPATH = [env.Dir('.')])