name: Build TPG Project

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
          sudo xargs --arg-file requirements.txt apt install

      - name: Set environment variables
        run: |
          echo "export TPG=${{ github.workspace }}/tpg" >> $GITHUB_ENV
          echo "export MUJOCO=<YOUR_PATH_TO_MUJOCO>/mujoco-3.2.2" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$MUJOCO/lib/" >> $GITHUB_ENV

      - name: Compile the project
        run: |
          cd src
          scons --opt

      - name: Run tests
        run: |
          # Add commands to run your tests here
          # Unit testing commands will be run here
          echo "Running tests..."