name: Build TPG Project

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          mkdir  ./mujoco
          wget https://github.com/google-deepmind/mujoco/releases/download/3.2.2/mujoco-3.2.2-linux-x86_64.tar.gz  -O ./mujoco/mujoco.tar.gz 
          tar -xzvf ./mujoco/mujoco.tar.gz -C ./mujoco
          if [ -d "./mujoco" ]; then
            echo "Mujoco folder created"
            echo "Files and directories in ~/.mujoco:"
            ls -l "./mujoco"  # List files and directories with details
          else 
              echo "Mujoco folder not created"
          fi
          cd src
          sudo xargs --arg-file requirements.txt apt install
          sudo apt-get install libglfw3 libglfw3-dev
          cd ../

             

      - name: Set environment variables
        run: |
          echo "export TPG=$(pwd)/src" >> $GITHUB_ENV
          echo "export PATH=$PATH:$(pwd)/tpg/scripts/plot" >> $GITHUB_ENV
          echo "export PATH=$PATH:$(pwd)/tpg/scripts/run" >> $GITHUB_ENV
          echo "export MUJOCO=$(pwd)/mujoco/mujoco-3.2.2" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/mujoco/mujoco-3.2.2/lib" >> $GITHUB_ENV

      - name: Print GitHub environment variables
        run: |
          echo "GitHub Environment Variables:"
          cat $GITHUB_ENV

      - name: Compile the project
        run: |
          cd src
          scons --opt

      - name: Run tests
        run: |
          # Add commands to run your tests here
          # Unit testing commands will be run here
          echo "Running tests..."
