name: cpp-linter

on:
  pull_request:
    branches:
      - main
    paths:
      - src/src/cpp/**
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          cd src
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo apt-get install -y gcc-13 g++-13
          sudo apt-get install -y libglfw3 libglfw3-dev libglew-dev
          sudo apt-get install -y bear
          sudo xargs --arg-file requirements.txt apt install

      # Set up Mujoco
      - name: Setup Mujoco
        run: |
          mkdir ./mujoco
          wget https://github.com/google-deepmind/mujoco/releases/download/3.2.2/mujoco-3.2.2-linux-x86_64.tar.gz -O ./mujoco/mujoco.tar.gz
          tar -xzvf ./mujoco/mujoco.tar.gz -C ./mujoco
          if [ -d "./mujoco" ]; then
            echo "Mujoco folder created"
            echo "Files and directories in ./mujoco:"
            ls -l "./mujoco"  # List files and directories with details
          else 
              echo "Mujoco folder not created"
          fi
          cd ../

      # Setup build environment
      - name: Setup build environment
        run: |
          echo "Setting up build environment..."
          ls
          ls src/
          echo $GITHUB_WORKSPACE
          echo "export TPG=$GITHUB_WORKSPACE/src" >> "$HOME/.bash_profile"
          echo "export PATH=$PATH:$GITHUB_WORKSPACE/src/scripts/plot" >>  "$HOME/.bash_profile"
          echo "export PATH=$PATH:$GITHUB_WORKSPACE/src/scripts/run" >>  "$HOME/.bash_profile"
          echo "export MUJOCO=$GITHUB_WORKSPACE/src/mujoco/mujoco-3.2.2" >>  "$HOME/.bash_profile"
          echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/src/mujoco/mujoco-3.2.2/lib" >>  "$HOME/.bash_profile"
          echo "MUJOCO=$GITHUB_WORKSPACE/src/mujoco/mujoco-3.2.2" >> "$GITHUB_ENV"
          source "$HOME/.bash_profile"
          
      # Generate compile_commands.json
      - name: Generate compilation database
        run: |
          cd src
          bear -- scons

      # Run cpp-linter with "file not found" suppression
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: "src/.clang-format"
          tidy-review: true
          database: "src/compile_commands.json"
          extra-args: "--warnings-as-errors=-clang-diagnostic-pp-file-not-found"

      # Fail if formatting checks fail
      - name: Fail fast?!
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: exit 1