name: Compile LaTeX Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**/*.tex"
  workflow_dispatch:

jobs:
  compile-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub App
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up LaTeX environment
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-science texlive-bibtex-extra texlive-publishers fonts-linuxlibertine

      - name: Find modified .tex files
        id: find_tex_files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.tex
          diff_relative: true
          files_ignore: |
            docs/Comments.tex
            docs/Common.tex
            docs/Reflection.tex

      - name: Compile LaTeX files
        if: steps.find_tex_files.outputs.any_changed == 'true'
        run: |
          for tex_file in ${{ steps.find_tex_files.outputs.all_changed_files }}; do
            file=$(basename -- "$tex_file")
            dir=$(dirname "$tex_file")
            cd "$dir"
            
            pdflatex "$file" || exit 1  # First compilation to generate .aux
            
            # Run BibTeX only if an .aux file exists
            if [ -f "${file%.tex}.aux" ]; then
              bibtex "${file%.tex}" || echo "BibTeX failed, but continuing..."
            fi
            
            pdflatex "$file" || exit 1  # Second compilation to resolve citations
            pdflatex "$file" || exit 1  # Third compilation for final references
            
            cd -
          done

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: --force docs/**/*.pdf
          message: Compiled Latex PDF
          author_name: github-actions
          author_email: github-actions@github.com
          push: false

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          branch: ${{ github.ref }}
